docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    - run:
        name: create upload folders
        command: mkdir -p files/upload_files && mkdir -p files/pixels
        service: nginx

environments:
  master:
    routes:
      - varnish:
          - "pixelsfordrupal.com"
          - "www.pixelsfordrupal.com"
